# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 341, 191))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.line_id = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_id.setReadOnly(False)
        self.line_id.setObjectName("line_id")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_id)
        self.line_title = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_title.setObjectName("line_title")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_title)
        self.line_roast = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_roast.setObjectName("line_roast")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_roast)
        self.line_ground = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_ground.setObjectName("line_ground")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_ground)
        self.line_about = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_about.setObjectName("line_about")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_about)
        self.line_price = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_price.setObjectName("line_price")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line_price)
        self.line_volume = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_volume.setObjectName("line_volume")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line_volume)
        self.commit_button = QtWidgets.QPushButton(Form)
        self.commit_button.setGeometry(QtCore.QRect(20, 240, 340, 23))
        self.commit_button.setObjectName("commit_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "Название"))
        self.label_3.setText(_translate("Form", "Обжарка"))
        self.label_4.setText(_translate("Form", "Молотый/в зёрнах"))
        self.label_5.setText(_translate("Form", "Описание вкуса"))
        self.label_6.setText(_translate("Form", "Цена"))
        self.label_7.setText(_translate("Form", "Объём упаковки"))
        self.commit_button.setText(_translate("Form", "Добавить/редактировать запись"))
